[build]
  command = "vite build"
  publish = "dist/client"

[dev]
  command = "vite dev"
  port = 3000

[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'"