/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosIndexRouteImport } from './routes/todos/index'
import { Route as TodosTodoIdRouteImport } from './routes/todos/$todoId'
import { Route as TodosTodoIdEditRouteImport } from './routes/todos/$todoId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIndexRoute = TodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosTodoIdRoute = TodosTodoIdRouteImport.update({
  id: '/todos/$todoId',
  path: '/todos/$todoId',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosTodoIdEditRoute = TodosTodoIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TodosTodoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todos/$todoId': typeof TodosTodoIdRouteWithChildren
  '/todos': typeof TodosIndexRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todos/$todoId': typeof TodosTodoIdRouteWithChildren
  '/todos': typeof TodosIndexRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/todos/$todoId': typeof TodosTodoIdRouteWithChildren
  '/todos/': typeof TodosIndexRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todos/$todoId' | '/todos' | '/todos/$todoId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todos/$todoId' | '/todos' | '/todos/$todoId/edit'
  id: '__root__' | '/' | '/todos/$todoId' | '/todos/' | '/todos/$todoId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodosTodoIdRoute: typeof TodosTodoIdRouteWithChildren
  TodosIndexRoute: typeof TodosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/': {
      id: '/todos/'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$todoId': {
      id: '/todos/$todoId'
      path: '/todos/$todoId'
      fullPath: '/todos/$todoId'
      preLoaderRoute: typeof TodosTodoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$todoId/edit': {
      id: '/todos/$todoId/edit'
      path: '/edit'
      fullPath: '/todos/$todoId/edit'
      preLoaderRoute: typeof TodosTodoIdEditRouteImport
      parentRoute: typeof TodosTodoIdRoute
    }
  }
}

interface TodosTodoIdRouteChildren {
  TodosTodoIdEditRoute: typeof TodosTodoIdEditRoute
}

const TodosTodoIdRouteChildren: TodosTodoIdRouteChildren = {
  TodosTodoIdEditRoute: TodosTodoIdEditRoute,
}

const TodosTodoIdRouteWithChildren = TodosTodoIdRoute._addFileChildren(
  TodosTodoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodosTodoIdRoute: TodosTodoIdRouteWithChildren,
  TodosIndexRoute: TodosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
